name: Shadow MinIO Upload
description: Upload file(s) to MinIO instance (self-hosted as well)
author: 'Shadow Walker'
branding:
  icon: upload-cloud
  color: purple
inputs:
  endpoint:
    description: MinIO endpoint (use `insecure=true` for HTTP-only)
    required: true
  access_key:
    description: MinIO access key
    required: true
  secret_key:
    description: MinIO secret key
    required: true
  bucket:
    description: Target bucket to upload file to
    required: true
  local_path:
    description: File in local
    required: true
  remote_path:
    description: Object path in MinIO's bucket (with a leading slash, default='/')
    required: false
    default: '/'
  insecure:
    description: Disables TLS/SSL certificate verification. Allows TLS connectivity to servers with invalid certificates.
    required: false
    default: 'false'
  recursive:
    description: If you specify a directory, you must also set `recursive=true` to recursively copy the contents of that directory. If you omit the `recursive` argument, action only copies objects in the top level of the specified directory.
    required: false
    default: 'false'
  api_signature_version:
    description: API signature version (S3v2, S3v4)
    required: false
    default: 'S3v4'
  extra_args:
    description: Use to add extra arguments to the command mc alias set
    required: false
    default: ''
  download:
    description: Download file(s) from MinIO instance
    default: 'false'

runs:
  using: docker
  image: Dockerfile
  env:
    YA_ENDPOINT: '${{ inputs.endpoint }}'
    YA_ACCESS_KEY: '${{ inputs.access_key }}'
    YA_SECRET_KEY: '${{ inputs.secret_key }}'
    YA_INSECURE: '${{ inputs.insecure }}'
    YA_RECURSIVE: '${{ inputs.recursive }}'
    YA_SIGNATURE_VERSION: '${{ inputs.api_signature_version }}'
    YA_EXTRA_ARGS: '${{ inputs.extra_args }}'
    YA_DOWNLOAD: '${{ inputs.download }}'
  args:
    - '${{ inputs.local_path }}'
    - '${{ inputs.bucket }}${{ inputs.remote_path }}'
