services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      YA_ENDPOINT: https://s3.ap-southeast-1.wasabisys.com
      YA_ACCESS_KEY: KC0MBKOXBUO8KC3LR1CZ
      YA_SECRET_KEY: TcpmbeAeqNooGYLNbSvCEOekr8gA8VrlCQ4efqv5s
      YA_SIGNATURE_VERSION: S3v4
      YA_EXTRA_ARGS: '--path off'
